name: Dart CI

on:
  release:
    branches:
      - master
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: dart:stable

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Generate code
        run: cd example && dart pub get && dart pub run build_runner build --delete-conflicting-outputs
      - name: Analyze packages
        run: PKGS="example retrofit generator" ./tool/travis.sh dartanalyzer
      - name: Install dependencies
        run: cd generator && dart pub get
      - name: Run tests
        run: |
          cd generator && dart pub run test

  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: generator